server:
    port: 8088
spring:
    application:
        name: projectlocator
    datasource:
        url: jdbc:postgresql://localhost:5432/db-project-locator?currentSchema="base"
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none


