server:
    port: 8088
spring:
    application:
        name: projectlocator
    datasource:
        url: jdbc:postgresql://3tk.h.filess.io:5433/dbprojectlocation_ishabitto?currentSchema="codetalkz"
        username: dbprojectlocation_ishabitto
        password: dc6cca2e5cec2c8db478030d3df9f8cba806111e
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none


